### ISSUE TITLE
[Error: _typeof is not a function (it is null)]

### ISSUE THREAD

**Issue by nick17728** [cawfree/react-native-wormhole#4]
Hi @cawfree , thanks for the amazing package , im a beginner and still trying to grasp the concept ,im getting the below error with reactnative expo 

babel version  8.15.0

### **File im trying to import wormhole** 
```
import React, { useState, useRef, useMemo, useCallback } from "react";
import { createWormhole } from "react-native-wormhole";

const { Wormhole } = createWormhole({
  verify: async () => true,
});

const HomePage = () => {

  return (
    <Wormhole
      source={{
        uri: "mydomain.ccr.com/test.js",
      }}
    />
  );
};

export default HomePage;
```

### **Sample JSX file**

```
import * as React from 'react';
import { Animated, Alert, TouchableOpacity } from 'react-native';

function CustomButton() {
  return (
    <TouchableOpacity onPress={() => Alert.alert('Hello!')}>
      <Animated.Text children="Click here!" />
    </TouchableOpacity>
  );
}

export default function MyNewWormhole() {
  const message = React.useMemo(() => 'Hello, world!', []);
  return (
    <Animated.View style={{ flex: 1, backgroundColor: 'red' }}>
      <Animated.Text>{message}</Animated.Text>
      <CustomButton />
    </Animated.View>
  );
}`
```

### **My transpiled js file**

`Object.defineProperty(exports,"__esModule",{value:true});exports.default=MyNewWormhole;var React=_interopRequireWildcard(require("react"));var _reactNative=require("react-native");var _jsxFileName="C:\\Users\\nickb\\Downloads\\MyNewWormhole.jsx";function _getRequireWildcardCache(e){if("function"!=typeof WeakMap)return null;var r=new WeakMap(),t=new WeakMap();return(_getRequireWildcardCache=function _getRequireWildcardCache(e){return e?t:r;})(e);}function _interopRequireWildcard(e,r){if(!r&&e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=_getRequireWildcardCache(r);if(t&&t.has(e))return t.get(e);var n={__proto__:null},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var u in e)if("default"!==u&&Object.prototype.hasOwnProperty.call(e,u)){var i=a?Object.getOwnPropertyDescriptor(e,u):null;i&&(i.get||i.set)?Object.defineProperty(n,u,i):n[u]=e[u];}return n.default=e,t&&t.set(e,n),n;}function CustomButton(){return React.createElement(_reactNative.TouchableOpacity,{onPress:function onPress(){return _reactNative.Alert.alert('Hello!');},__self:this,__source:{fileName:_jsxFileName,lineNumber:6,columnNumber:5}},React.createElement(_reactNative.Animated.Text,{children:"Click here!",__self:this,__source:{fileName:_jsxFileName,lineNumber:7,columnNumber:7}}));}function MyNewWormhole(){var message=React.useMemo(function(){return'Hello, world!';},[]);return React.createElement(_reactNative.Animated.View,{style:{flex:1,backgroundColor:'red'},__self:this,__source:{fileName:_jsxFileName,lineNumber:15,columnNumber:5}},React.createElement(_reactNative.Animated.Text,{__self:this,__source:{fileName:_jsxFileName,lineNumber:16,columnNumber:7}},message),React.createElement(CustomButton,{__self:this,__source:{fileName:_jsxFileName,lineNumber:17,columnNumber:7}}));}`

But  i get the following error 
![image](https://github.com/cawfree/react-native-wormhole/assets/29074273/4c5acc31-ec07-4dd9-9f77-e53281ed4359)

Any guidance /help will be appreciated

**Comment by twendykirn** [comment]
@nick17728 @cawfree Hi, i have the similar error and I was wondering about the possible solution.
